[package]
name = "server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "stealthvpn-server"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
rustls.workspace = true
tokio-rustls.workspace = true
serde.workspace = true
bincode.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tun.workspace = true
uuid.workspace = true
dashmap.workspace = true
clap.workspace = true
rand.workspace = true
x25519-dalek.workspace = true
